[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.155.1"
  HUGO_ENV = "production"

[context.production.environment]
  HUGO_ENVIRONMENT = "production"
